'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import "./globals.css";
import { useState } from "react";
import { RomContext } from "./RomContext";


const inter = Inter({ subsets: ["latin"] });

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [globalRom, setGlobalRom] = useState(null)
  const value = { globalRom, setGlobalRom };
  return (
    <html lang="en" style={{height: "100%", display: 'flex'}}>
      <body className={`${inter.className} display_flex`}>
        <AppRouterCacheProvider>
          <RomContext.Provider value={value}>
          {children}
          </RomContext.Provider>
        </AppRouterCacheProvider></body>
    </html>
  );
}
