'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import "./globals.css";
import { useState } from "react";
import { RomContext } from "./RomContext";
import { CssBaseline, ThemeProvider } from '@mui/material';
import { myTheme } from "./ThemeOptions";
import { Analytics } from "@vercel/analytics/react"


const inter = Inter({ subsets: ["latin"] });

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [globalRom, setGlobalRom] = useState(null)
  const value = { globalRom, setGlobalRom };
  return (
    <html lang="en" style={{height: '100%', display: 'flex', flexWrap: 'wrap', backgroundColor: 'black'}}>
      <body className={`${inter.className} display_flex`} style={{flexWrap: 'wrap', justifyContent: 'center'}}>
        <AppRouterCacheProvider>
          <RomContext.Provider value={value}>
          <ThemeProvider theme={myTheme}>
          <CssBaseline>
          {children}
          
          </CssBaseline>
          </ThemeProvider>
          </RomContext.Provider>
        </AppRouterCacheProvider>
        <Analytics />
        </body>
    </html>
  );
}
